using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BulletSpawner : MonoBehaviour
{
    public GameObject bulletPrefab;     // Original prefab of the bullet to be created
    public float spawnRateMin = 0.5f;   // Minimum generation period
    public float spawnRateMax = 3f;     // Maximum generation cycle

    private Transform target;           // Target to fire
    private float spawnRate;            // Generation period
    private float timeAfterSpawn;       // Time past the most recent generation point

    void Start()
    {
        // Initialize accumulated time to zero since the last generation
        timeAfterSpawn = 0f;
        // Randomly specify bullet generation interval between spawnRateMin and spawnRateMax
        spawnRate = Random.Range(spawnRateMin, spawnRateMax);
        // Locate a game object with a PlayerController component and set it as a target
        target = FindObjectOfType<PlayerController>().transform;
    }

    void Update()
    {
        // timeAfterSpawn renewal
        timeAfterSpawn += Time.deltaTime;
        // If the accumulated time from the last generation point is greater than or equal to the generation cycle,
        if (timeAfterSpawn>=spawnRate)
        {
            // Reset accumulated time
            timeAfterSpawn = 0f;
            // Copy of bulletPrefab
            // generated by rotation of transform.position position and transform.rotation
            GameObject bullet = Instantiate(bulletPrefab, transform.position, transform.rotation);
            // Rotate the generated bullet game object so that it faces the target
            bullet.transform.LookAt(target);
            // Randomly specify the next generation interval between spawnRateMin and spawnRateMax
            spawnRate = Random.Range(spawnRateMin, spawnRateMax);
        }
    }
}
